fix: CI.yml

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -37,12 +37,12 @@ jobs:
       - name: Compile Java code
         run: |
          javac -classpath ./Out/;./lib/mysql-connector-j-8.0.32.jar -d out Database/DB.java Main/Driver.java Main/Boundary/*.java Main/Boundary/Admin/*.java Main/Boundary/Customer/*.java Main/Boundary/Manager/*.java Main/Controller/*.java Main/Controller/Admin/*.java Main/Controller/Customer/*.java Main/Controller/Manager/*.java Main/Entity/*.java
-        if [ $? -eq 0 ]; then
-          echo "Compiled"
-        else
-          echo "Compilation failed"
-          exit 1
-        fi
+          if [ $? -eq 0 ]; then
+            echo "Compiled"
+          else
+            echo "Compilation failed"
+            exit 1
+          fi
   
 
       - name: Start Xvfb
